export type Bar={time:number;open:number;high:number;low:number;close:number};
export type Rule={kind:'ema'|'sma'|'rsi'|'bos'|'fvg';period:number;slow:number;level:number};
export type Strategy={id:string;name:string;timeframe:'H1'|'H4'|'D1';direction:'long'|'short'|'both';rules:Rule[];stop:number;rr:number;risk:number;version:number};
export type Settings={start:string;end:string;capital:number;spread:number;slippage:number;commission:number;source:string};
export type Trade={entryTime:number;exitTime:number;side:number;entry:number;exit:number;quantity:number;pnl:number;reason:string};
export type Result={strategy:Strategy;settings:Settings;bars:number;trades:Trade[];curve:{time:number;equity:number}[];net:number;drawdown:number;winRate:number;profitFactor:number|null;start:number;end:number};
export const ruleNames={ema:'EMA · tendencia',sma:'SMA · tendencia',rsi:'RSI · reversión',bos:'SMC · ruptura de estructura',fvg:'SMC · fair value gap'};
export function template(kind:Rule['kind']):Rule{return {kind,period:kind==='rsi'?14:20,slow:50,level:30}}
export function starter(index=0):Strategy{return {id:crypto.randomUUID(),name:['Tendencia dorada','Reversión RSI','Ruptura de estructura'][index]||'Nueva estrategia',timeframe:'H1',direction:'both',rules:[template((['ema','rsi','bos'] as const)[index%3])],stop:0.6,rr:2,risk:1,version:1}}
export function validateStrategy(s:Strategy){if(!s||!s.id||typeof s.name!=='string'||!s.name.trim()||s.name.length>80)throw Error('Escribe un nombre de hasta 80 caracteres.');if(!['H1','H4','D1'].includes(s.timeframe)||!['long','short','both'].includes(s.direction))throw Error('Temporalidad o dirección inválida.');if(!Array.isArray(s.rules)||!s.rules.length||s.rules.length>6)throw Error('Añade entre 1 y 6 condiciones.');for(const r of s.rules){if(!(r.kind in ruleNames)||!Number.isInteger(r.period)||r.period<2||r.period>200||!Number.isInteger(r.slow)||r.slow<2||r.slow>400||!Number.isFinite(r.level)||r.level<1||r.level>=50)throw Error('Revisa los períodos (2–200 / 2–400) y el umbral RSI (1–49).');if(['ema','sma'].includes(r.kind)&&r.period>=r.slow)throw Error('La media rápida debe tener menos períodos que la lenta.');}if(!Number.isFinite(s.stop)||s.stop<=0||s.stop>20||!Number.isFinite(s.rr)||s.rr<0.1||s.rr>20||!Number.isFinite(s.risk)||s.risk<=0||s.risk>10)throw Error('Revisa stop (0–20%), objetivo (0,1–20 R) y riesgo (0–10%).');}
export function moving(values:number[],period:number,ema:boolean){const out=Array(values.length).fill(NaN);let sum=0;for(let i=0;i<values.length;i++){sum+=values[i];if(i>=period)sum-=values[i-period];if(i===period-1||(!ema&&i>=period))out[i]=sum/period;else if(ema&&i>=period)out[i]=values[i]*2/(period+1)+out[i-1]*(1-2/(period+1));}return out;}
export function rsi(values:number[],n:number){const out=Array(values.length).fill(NaN);let up=0,down=0;for(let i=1;i<values.length;i++){const d=values[i]-values[i-1],u=Math.max(d,0),l=Math.max(-d,0);if(i<=n){up+=u/n;down+=l/n;}else{up=(up*(n-1)+u)/n;down=(down*(n-1)+l)/n;}if(i>=n)out[i]=down===0?(up===0?50:100):100-100/(1+up/down);}return out;}
export function aggregate(bars:Bar[],tf:Strategy['timeframe']){const step=({H1:1,H4:4,D1:24}[tf])*3600000;const out:Bar[]=[];for(const b of bars){const time=Math.floor(b.time/step)*step;const p=out.at(-1);if(p&&p.time===time){p.high=Math.max(p.high,b.high);p.low=Math.min(p.low,b.low);p.close=b.close;}else out.push({...b,time});}return out;}
export function signals(bars:Bar[],s:Strategy){const closes=bars.map(b=>b.close);const arrays=s.rules.map(r=>r.kind==='ema'||r.kind==='sma'?[moving(closes,r.period,r.kind==='ema'),moving(closes,r.slow,r.kind==='ema')]:r.kind==='rsi'?[rsi(closes,r.period)]:[]);return bars.map((b,i)=>{if(i<Math.max(...s.rules.map(r=>['ema','sma'].includes(r.kind)?r.slow:r.period)))return 0;const values=s.rules.map((r,k)=>{if(r.kind==='ema'||r.kind==='sma')return Math.sign(arrays[k][0][i]-arrays[k][1][i]);if(r.kind==='rsi'){const v=arrays[k][0][i],prev=arrays[k][0][i-1];return prev<r.level&&v>=r.level?1:prev>100-r.level&&v<=100-r.level?-1:0;}if(r.kind==='bos'){const prev=bars.slice(i-r.period,i);return b.close>Math.max(...prev.map(x=>x.high))?1:b.close<Math.min(...prev.map(x=>x.low))?-1:0;}return b.low>bars[i-2].high?1:b.high<bars[i-2].low?-1:0;});const d=values.every(x=>x===1)?1:values.every(x=>x===-1)?-1:0;return s.direction==='long'&&d<0||s.direction==='short'&&d>0?0:d;});}
export function backtest(input:Bar[],strategy:Strategy,settings:Settings):Result{
 validateStrategy(strategy);const {capital,spread,slippage,commission}=settings;const start=Date.parse(settings.start+'T00:00:00Z'),end=Date.parse(settings.end+'T23:59:59.999Z');if(!Number.isFinite(start)||!Number.isFinite(end)||end<start)throw Error('Selecciona un intervalo válido.');if(!Number.isFinite(capital)||capital<100||![spread,slippage,commission].every(x=>Number.isFinite(x)&&x>=0))throw Error('Capital mínimo: $100. Los costos deben ser positivos o cero.');
 const bars=aggregate(input,strategy.timeframe);const duration=({H1:1,H4:4,D1:24}[strategy.timeframe])*3600000;const indexes=bars.map((b,i)=>b.time>=start&&b.time+duration-1<=end?i:-1).filter(i=>i>=0);if(indexes.length<2)throw Error('No hay suficientes velas completas en ese período.');const sig=signals(bars,strategy);const warmup=Math.max(...strategy.rules.map(r=>['ema','sma'].includes(r.kind)?r.slow:r.period));if(indexes[0]<warmup)throw Error(`Faltan ${warmup-indexes[0]} velas previas para calcular los indicadores. Acorta el período o importa más historial.`);
 let equity=capital,peak=capital,dd=0;const trades:Trade[]=[],curve:{time:number;equity:number}[]=[];let p:{entry:number;side:number;quantity:number;stop:number;target:number;time:number}|null=null;const cost=spread/2+slippage;const mark=(e:number)=>{peak=Math.max(peak,e);dd=Math.max(dd,(peak-e)/peak*100);};
 function close(raw:number,b:Bar,reason:string){if(!p)return;const exit=raw-p.side*cost;const pnl=(exit-p.entry)*p.side*p.quantity-2*commission*p.quantity;equity+=pnl;trades.push({entryTime:p.time,exitTime:b.time,side:p.side,entry:p.entry,exit,quantity:p.quantity,pnl,reason});p=null;mark(equity);}
 for(const i of indexes){const b=bars[i],signal=sig[i-1]||0;if(p&&signal===-p.side)close(b.open,b,'Señal opuesta');if(!p&&signal&&equity>0){const entry:number=b.open+signal*cost;const distance:number=entry*strategy.stop/100;const quantity=Math.min(equity*strategy.risk/100/(distance+cost+2*commission),equity/entry);p={entry,side:signal,quantity,stop:entry-signal*distance,target:entry+signal*distance*strategy.rr,time:b.time};}
 if(p){const gapStop=p.side===1?b.open<=p.stop:b.open>=p.stop;const gapTarget=p.side===1?b.open>=p.target:b.open<=p.target;const stopHit=p.side===1?b.low<=p.stop:b.high>=p.stop;const targetHit=p.side===1?b.high>=p.target:b.low<=p.target;if(gapStop)close(b.open,b,'Stop · gap');else if(gapTarget)close(p.target,b,'Objetivo');else if(stopHit)close(p.stop,b,targetHit?'Stop · vela ambigua':'Stop');else if(targetHit)close(p.target,b,'Objetivo');else {const adverse=p.side===1?b.low:b.high;mark(equity+((adverse-p.side*cost)-p.entry)*p.side*p.quantity-2*commission*p.quantity);}}
 if(i===indexes.at(-1)&&p)close(b.close,b,'Fin del período');const current=p?equity+((b.close-p.side*cost)-p.entry)*p.side*p.quantity-2*commission*p.quantity:equity;mark(current);curve.push({time:b.time,equity:current});}
 const wins=trades.filter(t=>t.pnl>0),losses=trades.filter(t=>t.pnl<0);const grossLoss=-losses.reduce((a,t)=>a+t.pnl,0);return {strategy:structuredClone(strategy),settings:{...settings},bars:indexes.length,trades,curve,net:equity-capital,drawdown:dd,winRate:trades.length?wins.length/trades.length*100:0,profitFactor:grossLoss?wins.reduce((a,t)=>a+t.pnl,0)/grossLoss:null,start:bars[indexes[0]].time,end:bars[indexes.at(-1)!].time};
}
export function demoBars():Bar[]{let seed=431,price=2300;const random=()=>{seed=(Math.imul(1664525,seed)+1013904223)>>>0;return seed/4294967296;};const end=Date.UTC(2026,8,6),start=Date.UTC(2024,0,1);const out:Bar[]=[];for(let time=start;time<end;time+=3600000){if([0,6].includes(new Date(time).getUTCDay()))continue;const open=price;price=Math.max(500,price+(random()-.49)*14+Math.sin(out.length/100)*.6);out.push({time,open,close:price,high:Math.max(open,price)+random()*6,low:Math.min(open,price)-random()*6});}return out;}
export function parseCSV(text:string):Bar[]{const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/);if(lines.length>100001)throw Error('Máximo 100.000 velas por archivo.');const sep=lines[0].includes('\t')?'\t':lines[0].includes(';')?';':',';const clean=(s:string)=>s.trim().replace(/^"|"$/g,'').replace(/[<>]/g,'').toLowerCase();const headers=lines.shift()!.split(sep).map(clean);const index=(s:string)=>headers.indexOf(s);if(['open','high','low','close'].some(s=>index(s)<0)||index('time')<0)throw Error('Columnas requeridas: time, open, high, low, close. También se admite DATE + TIME de MT5.');const out:Bar[]=[];for(let n=0;n<lines.length;n++){if(!lines[n].trim())continue;const row=lines[n].split(sep).map(x=>x.trim().replace(/^"|"$/g,''));let date=index('date')>=0?row[index('date')].replaceAll('.','-')+'T'+row[index('time')]:row[index('time')];if(!/[zZ]$|[+-]\d\d:\d\d$/.test(date))date=date.replace(' ','T')+'Z';const time=Date.parse(date);const b={time,open:Number(row[index('open')]),high:Number(row[index('high')]),low:Number(row[index('low')]),close:Number(row[index('close')])};if(!Object.values(b).every(Number.isFinite)||Math.min(b.open,b.high,b.low,b.close)<=0||b.high<Math.max(b.open,b.close)||b.low>Math.min(b.open,b.close)||b.high<b.low||time%3600000!==0)throw Error(`Fila ${n+2}: OHLC inválido o fecha fuera de una hora exacta. Usa velas H1.`);out.push(b);}out.sort((a,b)=>a.time-b.time);if(out.some((b,i)=>i>0&&b.time-out[i-1].time<3600000))throw Error('Hay fechas duplicadas o velas menores a H1.');if(out.length<100)throw Error('Importa al menos 100 velas H1, incluyendo calentamiento.');return out;}

